<?php

declare(strict_types=1);

return [
    /*
     * Operations this package intends to support as local S3-compatible
     * functionality. Each entry must either have an AWS SDK functional test or
     * an explicit equivalent/alias in AwsSdkSupportMatrixTest.
     */
    'supported' => [
        'abortMultipartUpload',
        'completeMultipartUpload',
        'copyObject',
        'createBucket',
        'createMultipartUpload',
        'deleteBucket',
        'deleteBucketCors',
        'deleteBucketEncryption',
        'deleteBucketLifecycle',
        'deleteBucketPolicy',
        'deleteBucketTagging',
        'deleteBucketWebsite',
        'deleteObject',
        'deleteObjectTagging',
        'deleteObjects',
        'deletePublicAccessBlock',
        'getBucketAcl',
        'getBucketCors',
        'getBucketEncryption',
        'getBucketLifecycle',
        'getBucketLifecycleConfiguration',
        'getBucketLocation',
        'getBucketLogging',
        'getBucketNotification',
        'getBucketNotificationConfiguration',
        'getBucketPolicy',
        'getBucketPolicyStatus',
        'getBucketTagging',
        'getBucketVersioning',
        'getBucketWebsite',
        'getObject',
        'getObjectAcl',
        'getObjectAttributes',
        'getObjectLegalHold',
        'getObjectLockConfiguration',
        'getObjectRetention',
        'getObjectTagging',
        'getPublicAccessBlock',
        'headBucket',
        'headObject',
        'listBuckets',
        'listMultipartUploads',
        'listObjectVersions',
        'listObjects',
        'listObjectsV2',
        'listParts',
        'putBucketAcl',
        'putBucketCors',
        'putBucketEncryption',
        'putBucketLifecycle',
        'putBucketLifecycleConfiguration',
        'putBucketLogging',
        'putBucketNotification',
        'putBucketNotificationConfiguration',
        'putBucketPolicy',
        'putBucketTagging',
        'putBucketVersioning',
        'putBucketWebsite',
        'putObject',
        'putObjectAcl',
        'putObjectLegalHold',
        'putObjectLockConfiguration',
        'putObjectRetention',
        'putObjectTagging',
        'putPublicAccessBlock',
        'selectObjectContent',
        'uploadPart',
        'uploadPartCopy',
    ],

    /*
     * AWS-native S3 control-plane or adjacent operations that are not part of
     * this local filesystem-backed compatibility target. If one becomes a
     * product requirement, move it to supported and add functional coverage.
     */
    'unsupported' => [
        'createBucketMetadataConfiguration',
        'createBucketMetadataTableConfiguration',
        'createSession',
        'deleteBucketAnalyticsConfiguration',
        'deleteBucketIntelligentTieringConfiguration',
        'deleteBucketInventoryConfiguration',
        'deleteBucketMetadataConfiguration',
        'deleteBucketMetadataTableConfiguration',
        'deleteBucketMetricsConfiguration',
        'deleteBucketOwnershipControls',
        'deleteBucketReplication',
        'getBucketAbac',
        'getBucketAccelerateConfiguration',
        'getBucketAnalyticsConfiguration',
        'getBucketIntelligentTieringConfiguration',
        'getBucketInventoryConfiguration',
        'getBucketMetadataConfiguration',
        'getBucketMetadataTableConfiguration',
        'getBucketMetricsConfiguration',
        'getBucketOwnershipControls',
        'getBucketReplication',
        'getBucketRequestPayment',
        'getObjectTorrent',
        'listBucketAnalyticsConfigurations',
        'listBucketIntelligentTieringConfigurations',
        'listBucketInventoryConfigurations',
        'listBucketMetricsConfigurations',
        'listDirectoryBuckets',
        'putBucketAbac',
        'putBucketAccelerateConfiguration',
        'putBucketAnalyticsConfiguration',
        'putBucketIntelligentTieringConfiguration',
        'putBucketInventoryConfiguration',
        'putBucketMetricsConfiguration',
        'putBucketOwnershipControls',
        'putBucketReplication',
        'putBucketRequestPayment',
        'renameObject',
        'restoreObject',
        'updateBucketMetadataInventoryTableConfiguration',
        'updateBucketMetadataJournalTableConfiguration',
        'updateObjectEncryption',
        'writeGetObjectResponse',
    ],

    /*
     * Operations that can be meaningful with external AWS-compatible systems
     * such as KMS, IAM, STS, SNS/SQS, or control-plane integrations. They are
     * not required for the default local suite, but can be promoted to supported
     * by an integration test profile once such a service is wired in.
     */
    'optional_external' => [],
];
