<?php

declare(strict_types=1);

namespace OpsFour\S3Server\Symfony\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('opsfour_s3_server');

        $treeBuilder->getRootNode()
            ->children()
                ->arrayNode('server')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('host')->defaultValue('0.0.0.0')->end()
                        ->integerNode('port')->defaultValue(9000)->min(1)->max(65535)->end()
                        ->scalarNode('region')->defaultValue('us-east-1')->end()
                        ->scalarNode('tls_cert_path')->defaultNull()->end()
                        ->scalarNode('tls_key_path')->defaultNull()->end()
                        ->integerNode('max_connections')->defaultValue(10000)->min(1)->end()
                        ->integerNode('connection_idle_timeout')->defaultValue(60)->min(0)->end()
                        ->integerNode('body_size_limit')->defaultValue(5_368_709_120)->min(0)->end()
                        ->integerNode('read_timeout')->defaultValue(300)->min(0)->end()
                        ->integerNode('write_timeout')->defaultValue(300)->min(0)->end()
                        ->integerNode('rate_limit')->defaultValue(1000)->min(0)->end()
                        ->scalarNode('base_domain')->defaultNull()->end()
                        ->booleanNode('strict_bucket_naming')->defaultTrue()->end()
                        ->scalarNode('website_host_pattern')->defaultNull()->end()
                        ->scalarNode('master_key_provider')->defaultValue('config')->end()
                        ->booleanNode('enforce_min_part_size')->defaultFalse()->end()
                        ->integerNode('max_encrypted_object_size')->defaultValue(268_435_456)->min(0)->end()
                        ->integerNode('max_select_object_size')->defaultValue(268_435_456)->min(0)->end()
                        ->integerNode('shutdown_drain_timeout')->defaultValue(30)->min(1)->end()
                    ->end()
                ->end()
                ->arrayNode('storage')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->enumNode('driver')->values(['filesystem', 'flysystem', 'memory'])->defaultValue('filesystem')->end()
                        ->scalarNode('path')->defaultValue('/tmp/opsfour-s3-server')->end()
                        ->scalarNode('tier')->defaultValue('STANDARD')->end()
                        ->scalarNode('temp_dir')->defaultValue('/tmp')->end()
                        ->integerNode('worker_pool_size')->defaultValue(0)->min(0)->end()
                        ->scalarNode('filesystem_service')->defaultNull()->end()
                        ->scalarNode('filesystem_factory_service')->defaultNull()->end()
                        ->variableNode('filesystem')->defaultNull()->end()
                        ->variableNode('filesystem_factory')->defaultNull()->end()
                        ->arrayNode('tiers')
                            ->useAttributeAsKey('name')
                            ->arrayPrototype()
                                ->children()
                                    ->enumNode('driver')->values(['filesystem', 'flysystem', 'memory'])->defaultValue('filesystem')->end()
                                    ->scalarNode('path')->defaultNull()->end()
                                    ->booleanNode('restore_required')->defaultFalse()->end()
                                    ->booleanNode('default')->defaultFalse()->end()
                                    ->scalarNode('temp_dir')->defaultValue('/tmp')->end()
                                    ->integerNode('worker_pool_size')->defaultValue(0)->min(0)->end()
                                    ->scalarNode('filesystem_service')->defaultNull()->end()
                                    ->scalarNode('filesystem_factory_service')->defaultNull()->end()
                                    ->variableNode('filesystem')->defaultNull()->end()
                                    ->variableNode('filesystem_factory')->defaultNull()->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('metadata')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->enumNode('driver')->values(['sqlite', 'postgres', 'mysql'])->defaultValue('sqlite')->end()
                        ->scalarNode('dsn')->defaultValue('')->end()
                        ->scalarNode('path')->defaultNull()->end()
                        ->floatNode('cache_ttl')->defaultValue(5.0)->min(0)->end()
                    ->end()
                ->end()
                ->arrayNode('credentials')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->enumNode('driver')->values(['memory', 'database', 'file'])->defaultValue('memory')->end()
                        ->scalarNode('access_key')->defaultValue('testAccessKey')->end()
                        ->scalarNode('secret_key')->defaultValue('testSecretKey')->end()
                        ->scalarNode('owner_id')->defaultValue('default-owner')->end()
                        ->scalarNode('display_name')->defaultValue('Default User')->end()
                        ->scalarNode('dsn')->defaultNull()->end()
                        ->scalarNode('path')->defaultNull()->end()
                    ->end()
                ->end()
                ->arrayNode('admin')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('token')->defaultNull()->end()
                    ->end()
                ->end()
                ->arrayNode('external_iam')
                    ->normalizeKeys(false)
                    ->variablePrototype()->end()
                ->end()
                ->arrayNode('parallel')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('sqlite_workers')->defaultValue(0)->min(0)->end()
                        ->integerNode('encryption_workers')->defaultValue(0)->min(0)->end()
                        ->integerNode('request_body_spool_workers')->defaultValue(8)->min(1)->end()
                        ->integerNode('encryption_threshold')->defaultValue(65_536)->min(0)->end()
                    ->end()
                ->end()
                ->arrayNode('quotas')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('max_buckets_per_owner')->defaultValue(0)->min(0)->end()
                        ->integerNode('max_objects_per_bucket')->defaultValue(0)->min(0)->end()
                        ->integerNode('max_bytes_per_bucket')->defaultValue(0)->min(0)->end()
                        ->integerNode('max_bytes_per_owner')->defaultValue(0)->min(0)->end()
                    ->end()
                ->end()
                ->arrayNode('lifecycle')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->floatNode('interval_seconds')->defaultValue(60.0)->min(0.001)->end()
                        ->integerNode('batch_size')->defaultValue(1000)->min(1)->end()
                        ->integerNode('max_actions_per_run')->defaultValue(1000)->min(1)->end()
                        ->integerNode('lock_ttl_seconds')->defaultValue(300)->min(1)->end()
                    ->end()
                ->end()
                ->arrayNode('notifications')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('require_https')->defaultTrue()->end()
                        ->arrayNode('symfony_event_dispatcher')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('service')->defaultNull()->end()
                                ->scalarNode('pattern')->defaultValue('s3:*')->end()
                                ->scalarNode('event_name')->defaultNull()->end()
                            ->end()
                        ->end()
                        ->arrayNode('listeners')
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('event')->isRequired()->cannotBeEmpty()->end()
                                    ->scalarNode('service')->isRequired()->cannotBeEmpty()->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('encryption')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('service')->defaultNull()->end()
                        ->scalarNode('master_key_provider_service')->defaultNull()->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
